"use strict";
const state={conversation:null,provider:"openai"};
const $=id=>document.getElementById(id);
async function api(url,options={}){const r=await Auth.fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.detail||"请求失败");return data}
function renderMessages(messages){const box=$("messages");box.innerHTML="";if(!messages.length){box.innerHTML='<div class="welcome"><i class="fa-solid fa-sparkles"></i><h2>您好，我是平台助手</h2><p>可咨询工作台操作、项目数据管理、iServer 服务和土地资源评估流程。</p></div>';return}messages.forEach(m=>{const el=document.createElement("article");el.className=`message ${m.role}`;el.textContent=m.content;box.append(el)});box.scrollTop=box.scrollHeight}
async function loadConversation(id){state.conversation=id;const data=await api(`/api/ai/conversations/${id}/messages`);renderMessages(data.messages);const active=document.querySelector(".conversation.active");if(active)active.classList.remove("active");document.querySelector(`[data-id="${id}"]`)?.classList.add("active")}
async function refreshConversations(){const data=await api("/api/ai/conversations");const box=$("conversation-list");box.innerHTML="";data.conversations.forEach(c=>{const b=document.createElement("button");b.className="conversation";b.dataset.id=c.id;b.textContent=c.title;b.onclick=()=>loadConversation(c.id);box.append(b)});if(state.conversation)await loadConversation(state.conversation)}
async function createConversation(){const data=await api("/api/ai/conversations",{method:"POST",body:JSON.stringify({title:"新对话"})});state.conversation=data.conversation.id;$("conversation-title").textContent=data.conversation.title;await refreshConversations()}
$("new-chat").onclick=createConversation;
$("message-form").onsubmit=async e=>{e.preventDefault();const input=$("message-input"),content=input.value.trim();if(!content)return;if(!state.conversation)await createConversation();input.value="";try{const result=await api(`/api/ai/conversations/${state.conversation}/messages`,{method:"POST",body:JSON.stringify({content,provider:state.provider})});const before=await api(`/api/ai/conversations/${state.conversation}/messages`);renderMessages(before.messages);await refreshConversations()}catch(error){input.value=content;alert(error.message)}};
$("message-input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("message-form").requestSubmit()}};
$("settings-button").onclick=()=>$("settings-dialog").showModal();$("close-settings").onclick=$("cancel-settings").onclick=()=>$("settings-dialog").close();
$("settings-form").onsubmit=async e=>{e.preventDefault();try{const provider=$("provider").value.trim(),data=await api("/api/ai/providers",{method:"PUT",body:JSON.stringify({provider,base_url:$("base-url").value.trim(),model:$("model").value.trim(),api_key:$("api-key").value})});state.provider=data.provider;$("api-key").value="";$("settings-dialog").close()}catch(error){alert(error.message)}};
(async()=>{await Auth.checkAuth();const p=await api("/api/ai/providers");if(p.providers.length)state.provider=p.providers[0].provider;await refreshConversations();if(!state.conversation)await createConversation()})().catch(error=>alert(error.message));
