"""Real iServer-backed spatial operations used by land-resource assessment."""
from __future__ import annotations

import math
from typing import Any

from server.integrations import iserver_client


DEFAULT_CONSTRAINT_LAYERS = [
    {"datasource": "China100", "dataset": "Water_R", "label": "Water bodies", "kind": "water"},
    {"datasource": "China100", "dataset": "Lake_R", "label": "Lakes", "kind": "water"},
    {"datasource": "China100", "dataset": "MainRiver_R", "label": "Main river surfaces", "kind": "water"},
    {"datasource": "China100", "dataset": "MainRiver_L", "label": "Main river centerlines", "kind": "water"},
    {"datasource": "China100", "dataset": "River_L", "label": "River centerlines", "kind": "water"},
]

DEFAULT_ROAD_LAYERS = [
    {"datasource_name": "China100", "dataset_name": "NationalRd_L", "label": "National roads", "kind": "road"},
    {"datasource_name": "China100", "dataset_name": "Expressway_L", "label": "Expressways", "kind": "road"},
    {"datasource_name": "China100", "dataset_name": "ProvincialRd_L", "label": "Provincial roads", "kind": "road"},
]


def geometry_area_km2(geometry: dict[str, Any]) -> float:
    """Estimate geographic polygon area for reporting, not for cadastral measurement."""
    if geometry.get("type") == "Polygon":
        polygons = [geometry.get("coordinates", [])]
    elif geometry.get("type") == "MultiPolygon":
        polygons = geometry.get("coordinates", [])
    else:
        return 0.0
    total = 0.0
    for polygon in polygons:
        if not polygon:
            continue
        ring = polygon[0]
        if len(ring) < 4:
            continue
        twice_area = sum(
            ring[index][0] * ring[index + 1][1] - ring[index + 1][0] * ring[index][1]
            for index in range(len(ring) - 1)
        )
        latitude = sum(point[1] for point in ring) / len(ring)
        total += abs(twice_area) / 2 * 111.32**2 * math.cos(math.radians(latitude))
    return total


def _features_to_collection(query: dict[str, Any]) -> dict[str, Any]:
    features = []
    for raw_feature in query.get("features", []):
        geometry = raw_feature.get("geometry")
        if not geometry:
            continue
        properties = raw_feature.get("fieldValues") or raw_feature.get("attributes") or {}
        if isinstance(properties, list):
            fields = raw_feature.get("fieldNames") or []
            properties = dict(zip(fields, properties))
        features.append({"type": "Feature", "geometry": geometry, "properties": properties})
    return {"type": "FeatureCollection", "features": features}


def _feature_properties(raw_feature: dict[str, Any]) -> dict[str, Any]:
    properties = raw_feature.get("fieldValues") or raw_feature.get("attributes") or {}
    if isinstance(properties, list):
        properties = dict(zip(raw_feature.get("fieldNames") or [], properties))
    return properties if isinstance(properties, dict) else {}


def compute_buffer_stats(geometry: dict[str, Any], buffer_distance: float) -> dict[str, Any]:
    """Create a real iServer buffer and return it as a map-ready GeoJSON result."""
    result = iserver_client.spatial_buffer(geometry, buffer_distance)
    buffer_geometry = result["resultGeometry"]
    return {
        "buffer_area_km2": round(geometry_area_km2(buffer_geometry), 3),
        "distance_m": result["distance_m"],
        "distance_mode": result["distance_mode"],
        "source": result["source"],
        "resource_url": result["resource_url"],
        "visualization": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": buffer_geometry,
                "properties": {"operation": "buffer", "distance_m": result["distance_m"]},
            }],
        },
        "note": "Buffer geometry was generated by the published iServer Spatial Analyst service.",
    }


def overlay_constraint_stats(
    parcel_geojson: dict[str, Any],
    constraint_datasets: list[str] | None = None,
) -> dict[str, Any]:
    """Query published water polygons that truly intersect the assessment boundary."""
    selected = {name.strip() for name in constraint_datasets or [] if name.strip()}
    layers = [layer for layer in DEFAULT_CONSTRAINT_LAYERS if not selected or layer["dataset"] in selected]
    summaries = []
    map_features = []
    for layer in layers:
        query = iserver_client.query_features_by_geometry(
            layer["datasource"], layer["dataset"], parcel_geojson, max_features=200
        )
        collection = _features_to_collection(query)
        map_features.extend(collection["features"])
        summaries.append({
            "dataset": layer["dataset"],
            "label": layer["label"],
            "feature_count": query["feature_count"],
            "returned_feature_count": len(collection["features"]),
            "resource_url": query["resource_url"],
        })
    return {
        "parcel_area_km2": round(geometry_area_km2(parcel_geojson), 3),
        "layer_summaries": summaries,
        "feature_count": sum(item["feature_count"] for item in summaries),
        "queried_layers": [item["dataset"] for item in summaries],
        "source": "iserver:data-China100",
        "visualization": {"type": "FeatureCollection", "features": map_features},
        "note": (
            "The result uses exact spatial intersections against published lake, water-surface, and river-centerline layers. "
            "A zero result means no feature from those published China100 layers intersects the selected boundary."
            if map_features else
            "No published China100 water-surface or river-centerline feature intersects the selected boundary. "
            "Satellite imagery may contain smaller or newer water features that are not represented at this dataset scale."
        ),
    }


def road_accessibility(
    parcel_geojson: dict[str, Any],
    layers: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Query road features intersecting the assessment boundary."""
    selected_layers = layers or DEFAULT_ROAD_LAYERS
    summaries = []
    map_features = []
    for layer in selected_layers:
        datasource = layer.get("datasource_name") or layer.get("datasource")
        dataset = layer.get("dataset_name") or layer.get("dataset")
        if not datasource or not dataset:
            continue
        query = iserver_client.query_features_by_geometry(datasource, dataset, parcel_geojson, max_features=200)
        collection = _features_to_collection(query)
        map_features.extend(collection["features"])
        summaries.append({
            "dataset": dataset,
            "label": layer.get("label") or dataset,
            "feature_count": query["feature_count"],
            "returned_feature_count": len(collection["features"]),
            "resource_url": query["resource_url"],
        })
    return {
        "feature_count": sum(item["feature_count"] for item in summaries),
        "layers": summaries,
        "source": "iserver:data-China100",
        "visualization": {"type": "FeatureCollection", "features": map_features},
        "note": "This is a spatial intersection result. Road proximity needs a projected distance analysis or a dedicated network service.",
    }


def administrative_context(parcel_geojson: dict[str, Any]) -> dict[str, Any]:
    """Locate the parcel within the published China100 administrative polygons."""
    query = iserver_client.query_features_by_geometry("China100", "Province_R", parcel_geojson, max_features=20)
    collection = _features_to_collection(query)
    names = []
    name_fields = ("NAME", "NAMECHN", "NAME_CN", "NAMECHINESE", "Name", "name")
    for raw_feature in query.get("features", []):
        properties = _feature_properties(raw_feature)
        name = next((properties.get(key) for key in name_fields if properties.get(key)), None)
        if name and name not in names:
            names.append(str(name))
    for feature in collection["features"]:
        feature["properties"] = {
            **feature.get("properties", {}),
            "operation": "admin_context",
            "administrative_name": next(
                (name for name in names if name),
                "Administrative area",
            ),
        }
    return {
        "feature_count": query["feature_count"],
        "administrative_names": names,
        "source": query["source"],
        "resource_url": query["resource_url"],
        "visualization": collection,
        "note": (
            f"Located in: {'、'.join(names)}."
            if names else
            "No administrative polygon from the published China100 province layer intersects the selected boundary."
        ),
    }
